theme: jekyll-theme-cayman
title: My tryst with AI/ML Journey
description: Blog sharing my experiences & experiments in learning ML from scratch
author:  Shivam Sinha
baseurl:
google_analytics: UA-128434218-1
github:
  is_project_page: false
plugins:
  - jekyll-seo-tag
defaults:
  - scope:
      path: "assets"
    values:
      image: true