theme: jekyll-theme-cayman
title: My tryst with AI/ML Journey
description: Blog sharing my experiences & experiments in learning ML from scratch
baseurl: /TPE
google_analytics: UA-128434218-1
github:
  is_project_page: false